test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... FAIL
test_summation (__main__.TestExercice) ... ok

======================================================================
FAIL: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 20, in test_prefixes
    'Mauvaise identification de la parit√© de la longueur de la chaine'
AssertionError: First sequence is not a list: 'list[Jack, Kack, Lack, Mack, Nack, Oack, Pack, Qack]'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=1)
